{
 "title": "Momo-store business",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "id", "query": { "query": "label_values(id)" } },
   { "name": "handler", "query": { "query": "label_values(handler)" } },
   { "name": "le", "query": { "query": "label_values(le)" } }
  ]
 },
 "panels": [
  {
   "title": "Respons Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "response_timing_ms_bucket{handler=~\"$handler\",le=~\"$le\"}",
     "legendFormat": "response_timing for \"$handler\""
    }
   ]
  },
  {
   "title": "Листинг пельменей по видам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "dumplings_listing_count{id=~\"$id\"}",
     "legendFormat": "listing_count with id = {{id}}"
    }
   ]
  },
  {
   "title": "Количество заказов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "orders_count", "legendFormat": "orders_count" }
   ]
  },
  {
   "title": "Количество запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "requests_count", "legendFormat": "requests_count" }
   ]
  }
 ]
}