# Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJzdGQtMDQzLTI4IiwicGFzc3dvcmQiOiI4a3NacDU2UyIsImF1dGgiOiJjM1JrTFRBME15MHlPRG80YTNOYWNEVTJVdz09In19fQo=
type: kubernetes.io/dockerconfigjson
