stages:
  - release
  - deploy

release-to-nexus:
  stage: release
  image: alpine/helm:3.16.2
  script:
    - cd infrastructure/momo-store-chart
    - helm package --dependency-update . --version ${CI_PIPELINE_ID}
    - curl -L -u $NEXUS_USER:$NEXUS_PASS $NEXUS_HELM_REPO --upload-file *.tgz -v

deploy-to-kubernetes:
  stage: deploy
  image: alpine/helm:3.16.2
  needs:
    - release-to-nexus
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
    - apk add jq
  script:
    - cd infrastructure/momo-store-chart
    - helm upgrade --dependency-update --install --atomic --timeout 15m -n momo-store momo-store . --set grafana.adminPassword=$GRAFANA_ADM_PWD
    - rm ~/.kube/config
  when: manual
